"""third migration

Revision ID: 280f414ccf61
Revises: 12882ae8d8da
Create Date: 2023-03-01 11:07:57.280941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280f414ccf61'
down_revision = '12882ae8d8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
