"""initial migration

Revision ID: 928f6781a00b
Revises: 
Create Date: 2023-02-27 13:57:40.604346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928f6781a00b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=56), nullable=True),
    sa.Column('lastName', sa.String(length=56), nullable=True),
    sa.Column('email', sa.String(length=56), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
